# -*- mode: yaml -*-

version: 2
jobs:
  test-1.11:
    working_directory: /go/src/go.universe.tf/goppp
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - setup_remote_docker
      - run: GO111MODULE=on go test -v ./...
      - run: cd test && docker build -t goppp:testing .
workflows:
  version: 2
  test:
    jobs:
      - test-1.11:
          filters:
            tags:
              only: /.*/
